### ISSUE TITLE
loadmap

### ISSUE THREAD

**Issue by kazupon** [kazupon/vue-validator#24]
# v1.0.7

This version is the last of supported version of Vue.js 0.11.
- [x] unbind bug fix #19 
# v1.1.0

This version is supported Vue.js 0.12.
- [x] support Vue.js 0.12 (#23)
- [x] pattern validator change (pattern validator bug fix #17)
# v.1.1.0 later
- [x] delay initialize of validation (#25)
- [x] v-validate reactive (#6)
- [x]  function or inline expression like `v-on` (#40)
- [x] async validation (#10)
# v2.0

This version is implemented with full scratch and new design

~~\- [ ] v-validate reactive (#6)~~
~~\- [ ] async validation (#10)~~
- [x] improve delay initialize of validation (wait-for) (#25)
  ~~\- [ ] array-able validation (#31)~~
- [x] improve/add validation property (`dirty`, `pristine`, and other) (#33)
  ~~\- [ ] input[type='file'] validation~~
  ~~- [ ] add build-in validators ~~
- [x] dynamic validator setup (#46)
- [x] multiple validators (#18)
  ~~\- [ ] HTML5 form attributes (#22)~~
- [x] invalid error message (#51)
- [x] input debounce for async validation (#58)
- [x] events triggering (blur, submit, keyup, ... etc)

~~# v3.0~~
~~\- [ ] input[type='file'] validation~~
